const COLORS = { lightgray: { label: 'Light gray', hex: '#cbd0d6' }, red: { label: 'Red', hex: '#ef4444' }, blue: { label: 'Blue', hex: '#3b82f6' }, green: { label: 'Green', hex: '#22c55e' } };
const saved = JSON.parse(localStorage.getItem('bobloxState') || '{}');
const state = { selected: saved.selected || null, owned: new Set(saved.owned || []) };
function save() { localStorage.setItem('bobloxState', JSON.stringify({ selected: state.selected, owned: [...state.owned] })); }
function colorHex() { return (COLORS[state.selected] || COLORS.lightgray).hex; }
function paintAvatar(element) { if (!element) return; element.style.setProperty('--avatar-color', colorHex()); }
function paintAll() { document.querySelectorAll('.avatar').forEach(paintAvatar); }
function renderShop() { document.querySelectorAll('.buy-button').forEach((button) => { const owned = state.owned.has(button.dataset.color); button.textContent = owned ? (state.selected === button.dataset.color ? 'Wearing' : 'Owned') : 'Get'; button.classList.toggle('owned', owned); }); }
function renderOwned() { const container = document.querySelector('#owned-colors'); if (!container) return; const items = [...state.owned]; container.innerHTML = items.length ? items.map((color) => `<button class="owned-item ${state.selected === color ? 'selected' : ''}" data-color="${color}" type="button"><span class="swatch ${color}-swatch"></span><span><strong>${COLORS[color].label}</strong><small>${state.selected === color ? 'Currently wearing' : 'Click to wear'}</small></span><span class="check">${state.selected === color ? '✓' : ''}</span></button>`).join('') : '<p class="empty-message">You do not own any colors yet. Visit the Shop to get one for free.</p>'; container.querySelectorAll('.owned-item').forEach((item) => item.addEventListener('click', () => { const color = item.dataset.color; state.selected = state.selected === color ? null : color; save(); renderOwned(); paintAll(); })); }
const menu = document.querySelector('.triple-bar'); const side = document.querySelector('#side-menu');
if (menu && side) menu.addEventListener('click', () => { const open = side.classList.toggle('is-open'); menu.setAttribute('aria-expanded', open); side.setAttribute('aria-hidden', !open); });
document.querySelectorAll('.buy-button').forEach((button) => button.addEventListener('click', () => { const color = button.dataset.color; state.owned.add(color); state.selected = state.selected === color ? null : color; if (state.selected === null && state.owned.has(color)) { state.selected = color; } save(); renderShop(); paintAll(); }));
const reset = document.querySelector('#reset-state'); if (reset) reset.addEventListener('click', () => { state.selected = null; save(); paintAll(); renderOwned(); renderShop(); });
renderShop(); renderOwned(); paintAll();
